id: P97276222
initial_creation_type: input
source_metadata:
  title: Lama Zhang Tsöndrü Drakpa
  language: bo
  description: 'Texts by and about Lama Zhang Tsöndrü Drakpa (bla ma zhang brtson
    ''grus grags pa, 1123–1193), founder of the Tsalpa Kagyü:'
  volume:
    a44bd13ee35441a6b92b7483bca65949:
      title: Twelve and a Half Crippled Verses
      parent: Songs and Poems
created_at: '2022-03-01T00:34:12.189392'
last_modified_at: '2022-03-01T00:34:12.189394'
statistics:
  total_words: 195
  total_non_words: 24
quality:
  non_words_ratio: 0.12
